### ISSUE TITLE
utils\SimBiber.py中的bug

### ISSUE THREAD

**Issue by ustc-zhu** [MLNLP-World/SimBiber#1]
需要在utils\SimBiber.py下第75行前加上self.bib = Bib(self.args)，否则会报错

**Comment by LightChen233** [comment]
> 需要在utils\SimBiber.py下第75行前加上self.bib = Bib(self.args)，否则会报错
非常感谢您的意见，我们现在已经修复了这个bug，并将您添加在贡献者中，再次感谢
