### ISSUE TITLE
似乎会把*ACL 都简化为proc.ACL

### ISSUE THREAD

**Issue by Los-Phoenix** [MLNLP-World/SimBiber#2]
没有细看代码；似乎是因为ACL的全称是EACL等的字串，优先匹配了。

把ACL行移到最下面会暂时缓解这个问题，

例：
@inproceedings{DBLP:conf/eacl/BunescuP06,
  author    = {Razvan C. Bunescu and
               Marius Pasca},
  editor    = {Diana McCarthy and
               Shuly Wintner},
  title     = {Using Encyclopedic Knowledge for Named entity Disambiguation},
  booktitle = {{EACL} 2006, 11st Conference of the European Chapter of the Association
               for Computational Linguistics, Proceedings of the Conference, April
               3-7, 2006, Trento, Italy},
  publisher = {The Association for Computer Linguistics},
  year      = {2006},
  url       = {https://aclanthology.org/E06-1002/},
  timestamp = {Fri, 06 Aug 2021 00:40:45 +0200},
  biburl    = {https://dblp.org/rec/conf/eacl/BunescuP06.bib},
  bibsource = {dblp computer science bibliography, https://dblp.org}
}

**Comment by LightChen233** [comment]
在最新版本中，我们已经对您提出的问题进行了修复，感谢你对我们工作的支持
