### ISSUE TITLE
Why not retain more information?

### ISSUE THREAD

**Issue by yuezih** [MLNLP-World/SimBiber#5]
是否可以像Rebiber一样，更改必要信息的同时保留原始`.bib`文件中存在的其它信息，为用户提供更多选择？如我现在只想缩写会议名称，但仍需保留页码，用Simbiber会带来一些不便。
如果这背离了你们的初衷，也可以考虑将其作为可选功能，需在命令行中指定。
Thanks a lot.

**Comment by LightChen233** [comment]
Thanks for your issue, we have supported this feature in the latest version of Simbiber.
