### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by BD-MF** [MLNLP-World/SimBiber#6]
FileNotFoundError: [Errno 2] No such file or directory: 'keep_keys.cfg'

**Comment by LightChen233** [comment]
In the latest version, we fixed this bug, thanks for your issue.

**Comment by PirateX0** [comment]
In the latest version (until 2023.4.2), the above error still exists. 
A simple workaround is to manually create an empty keep_keys.cfg file in the directory where the bib is located.

**Comment by PirateX0** [comment]
Thank you for providing this excellent tool. 
It is quite helpful for formatting references and is easy to use!

A tip for this issue:
In the latest version (until 2023.4.2), the above error still exists.
A simple workaround is to _manually create a keep_keys.cfg file in the directory where the bib file is located_.
